reddit_client_secret = "09sqx0ogd2JuhZKo876QG2LuV414QQ"
reddit_client_id = "Q7vRLdxBAK1tXFIN6zVtkg"
reddit_user_agent = "macos:com.example.myredditapp:v1.1.1"
AWS_ACCESS_KEY_ID = "AKIA5JY2GBULGIDGH26U"
AWS_SECRET_ACCESS_KEY = "BIz2d0dugOzflS9SF8KiAJvZ3+m1TeeyLiVQWIOo"